---
name: CenFuzz

on:
 push:
   paths:
   - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - name: Build CenFuzz
      run: |
        go build -v ./...
...
